### ISSUE TITLE
Pattern Library

### ISSUE THREAD

**Issue by lehmana** [Project-BoxSand/boxsand#1]

**Comment by lehmana** [comment]
I need to get some feedback on the progress I have made

**Comment by lehmana** [comment]
<img width="336" alt="screen shot 2018-02-03 at 10 48 15 am" src="https://user-images.githubusercontent.com/25087441/36043038-caa6b69a-0d82-11e8-89ad-4ff4aae24214.png">

**Comment by lehmana** [comment]
Thoughts on this logo idea? @SamMorey @maxmoulds  (it's very rough I know, I don't want to waste time polishing)

**Comment by maxmoulds** [comment]
nice!. works for me.
